include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = NSBezierPathTest
NSBezierPathTest_HEADERS = BezierPathView.h
NSBezierPathTest_OBJC_FILES = main.m BezierPathView.m

include $(GNUSTEP_MAKEFILES)/application.make