name: Run GNUstep tests

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Update APT
      run: |
        sudo apt-get update
    - name: Setup Python
      uses: actions/setup-python@v3
    - name: Install dependencies
      run: |
        sudo apt-get install -y gnustep gnustep-devel
        sudo apt-get install -y xvfb imagemagick xdotool
    - name: Prepare GNUStep make and compile
      run: |
        . /usr/share/GNUstep/Makefiles/GNUstep.sh
        cd Applications/HelloWorld
        make
        cd ../NSBezierPathTest
        make
        cd ../RectFill
        make
    - name: Take Graphics Screenshots
      run: |
        Xvfb :1 &
        export DISPLAY=:1
        openapp Applications/NSBezierPathTest/NSBezierPathTest.app &
        sleep 5
        import -display :1 -window "NSBezierPathTestApp" NSBezierPathTestApp.png
        openapp Applications/RectFill/RectFillTest.app &
        sleep 5
        active_window_id=$(xdotool getwindowfocus)
        import -display :1 -window $active_window_id RectFillTestApp.png
    - name: Run tests
      run: |
        ls
        python3 -m unittest



    
